name: flutter_bloc_authentication
description: A simple Flutter project that showcases how to use the BLoC pattern for authentication.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2

  flutter:
    sdk: flutter

 
 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
 
 
  uses-material-design: true

 
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
